version: '3'
services:
  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    links:
      - mongo:mongo
    depends_on:
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  mongo:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
